name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/*.rst'
      - '**/*.md'

jobs:

   run-tests:
     runs-on: ubuntu-latest
     timeout-minutes: 30
     strategy:
       max-parallel: 15
       matrix:
         python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
     env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: true
     name: Python ${{ matrix.python-version }} test
     steps:
       - uses: actions/checkout@v2
       - name: install python
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}

       - name: Install Poetry
         uses: dschep/install-poetry-action@v1.3

       - name: cache
         uses: actions/cache@v1
         id: cache
         with:
           path: ~/.virtualenvs
           key: poetry-${{ hashFiles('**/poetry.lock') }}
           restore-keys: |
             poetry-${{ hashFiles('**/poetry.lock') }}

       - name: install redis
         run: |
           sudo apt-get update
           sudo apt-get install -y redis
       - name: run tests
         run: |
           pip install -r dev_requirements.txt
           tox -e python${{ matrix.python-version }}
       - name: build and install the package in this python version
         run: |
           poetry build
           poetry install
       - name: Upload codecov coverage
         uses: codecov/codecov-action@v2
         with:
           fail_ci_if_error: false
           token: ${{ secrets.CODECOV_TOKEN }}
