name: Publish Pypi
on:
  release:
    types: [ published ]

jobs:
  pytest:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@master

      - name: get version from tag
        id: get_version
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.9

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          pip install poetry
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry version ${{ steps.get_version.outputs.VERSION }}

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Publish to PyPI
        if: github.event_name == 'release'
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }} --build
